### ISSUE TITLE
Blocked by Antivirus because of malicious content

### ISSUE THREAD

**Issue by TrickyMikey2000** [LearningKijo/MDEtester#2]
Running the MDEtesterWP.ps1 on an onboarded MDE Windows client brings me the message "blocked by Antivirus due to malicious content" - I can't run the script.

**Comment by LearningKijo** [comment]
Thank you for your feedback. I tested it again in my environment, but the file was not blocked even though the antivirus was enabled. As a prerequisite, the script must be run as an administrator.
